account:
  type: 1
  username: tungminh111
  password: nguyennhatminhvip99@
  balance_info: 
    asset_infos:
      - type: "BTC"
        balance: 1000.12
algorithm:
  type: 1
  observe_sticks: 5
reader:
  type: 1
  file_path: "input"
  cur_time: 1666310300009
  kline_interval: 60001
output:
  enable_calling_api: false 
  file_writer:
    dummy: dummy
  api_caller:
    dummy: dummy
